### PR TITLE
[#2] adding timeout to pgsql:squery

### PR DESCRIPTION
**Pull request by ferigis**
I have created a function pgsql:squery/3 with Timeout parameter. This is related with #2

### CODE REVIEW

**Comment by ferigis** [comment]
Hi! I would like to know if you are going to merge this PR. Is it fine for you?

**Comment by ferigis** [comment]
Hi Guys, any update on this? It would be great allowing custom timeouts on squery function :)

**Comment by zinid** [comment]
Sorry for the delay

**Comment by ferigis** [comment]
Thanks @zinid ! :)

**Pull request merged**
